// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSE-lQZb5LbQyrj-MmDe8TPoJLG9o5iF8',
    appId: '1:934390734160:web:76d3b79c8108beda42a055',
    messagingSenderId: '934390734160',
    projectId: 'digitalburnoutdetection',
    authDomain: 'digitalburnoutdetection.firebaseapp.com',
    storageBucket: 'digitalburnoutdetection.firebasestorage.app',
    measurementId: 'G-3EV0YENSSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO-ISlevuBfle4lOAdALulfBICMTtLYtY',
    appId: '1:934390734160:android:54c19a62119ba27142a055',
    messagingSenderId: '934390734160',
    projectId: 'digitalburnoutdetection',
    storageBucket: 'digitalburnoutdetection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgxXxbajv7QjsiauRv2K-rTeCcd3IGrdk',
    appId: '1:934390734160:ios:d8eeec6e20abf02e42a055',
    messagingSenderId: '934390734160',
    projectId: 'digitalburnoutdetection',
    storageBucket: 'digitalburnoutdetection.firebasestorage.app',
    iosBundleId: 'com.example.flutterCatalog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgxXxbajv7QjsiauRv2K-rTeCcd3IGrdk',
    appId: '1:934390734160:ios:d8eeec6e20abf02e42a055',
    messagingSenderId: '934390734160',
    projectId: 'digitalburnoutdetection',
    storageBucket: 'digitalburnoutdetection.firebasestorage.app',
    iosBundleId: 'com.example.flutterCatalog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSE-lQZb5LbQyrj-MmDe8TPoJLG9o5iF8',
    appId: '1:934390734160:web:eb38580fae09467942a055',
    messagingSenderId: '934390734160',
    projectId: 'digitalburnoutdetection',
    authDomain: 'digitalburnoutdetection.firebaseapp.com',
    storageBucket: 'digitalburnoutdetection.firebasestorage.app',
    measurementId: 'G-11TNBJRZPM',
  );
}
